# Generated by Django 2.2 on 2019-12-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationManager',
        ),
    ]
